countries_cities = [
    ("United States", "New York"),
    ("France", "Paris"),
    ("Germany", "Berlin"),
    ("Japan", "Tokyo"),
    ("China", "Beijing"),
    ("Spain", "Madrid"),
    ("Italy", "Rome"),
    ("Russia", "Moscow"),
    ("Brazil", "São Paulo"),
    ("India", "Mumbai"),
    ("Canada", "Toronto"),
    ("Mexico", "Mexico City"),
    ("South Korea", "Seoul"),
    ("United Kingdom", "London"),
    ("Saudi Arabia", "Riyadh"),
    ("Australia", "Sydney"),
    ("Egypt", "Cairo"),
    ("Turkey", "Istanbul"),
    ("Nigeria", "Lagos"),
    ("South Africa", "Johannesburg"),
    ("Argentina", "Buenos Aires"),
    ("Sweden", "Stockholm"),
    ("Norway", "Oslo"),
    ("Netherlands", "Amsterdam"),
    ("Switzerland", "Zurich"),
    ("Thailand", "Bangkok"),
    ("Vietnam", "Hanoi"),
    ("Indonesia", "Jakarta"),
    ("Philippines", "Manila"),
    ("Pakistan", "Karachi")
]
